### ISSUE TITLE
Add dividing lines between packing slots or dates when ordering by those columns

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#152]
### Describe the solution / feature you'd like

In the warehouse we have 2 packing shifts when parcels are packed, either in the morning (AM) or afternoon (PM). 

However at Christmas, we change from 2 Shifts (AM/PM) to 4 Shift (Shift 1, Shift 2, Shift 3, Shift 4). 

Admin needs to be able to edit these to reflect what season we are in. 

We also have a Shift called Supplies (people who don't get food, but get items like Plates/Cutlery/Bedding/Clothes, and a Shift called Spanish. We use packing shifts as a natural divide on the parcels page to help the manager see the different amount of parcels in each shift, and to say "This person is special and in a category" or, for the callers team, to say, hey, don't ring this client unless you speak spanish...or to our spanish caller, you can easily find all the clients you need to ring in the Spanish section on the page.

All Shifts should have a dividing line between them (like current app) to make it really obvious where the divide is between different shifts

<img width="1411" alt="Screenshot 2024-03-14 at 22 42 13" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/80202270/929d81e9-5d09-462f-84c8-6ed043f85967">

**Comment by rickaw** [comment]
Hey @dan-langridge, thanks for raising this. 

- The ability to add packing slots, and to swtich on and off particular slots is currently being worked on currently with [VFB-37](https://softwiretech.atlassian.net/browse/VFB-37).
- The greeen dividing line between shifts is something new. We'll get working on that soon. Just to clarify, do we want to show the divider only when sorting the parcels by the packing slots ("Time" column in your image)? i.e. No need to show the line when sorting by something else?

**Comment by dan-langridge** [comment]
Thanks Ricky.

I agree with your point, the dividing line would only be required when sorting by:
- Packing Slot (AM/PM)
- Date (if we are viewing parcels across multiple days for example, helpful to have a divider between days)

Thanks
Dan

**Comment by KylePUG** [comment]
## QA 

- Use light mode for this first section
- Navigate to parcels page and sort by packing slots
- [x] Green dividing lines should appear between rows of distinct packing slots
- Increase date range across multiple days and sort by packing dates
- [x] Green dividing lines should appear between rows of distinct days 
- [x] Thinner light green dividing lines should also appear between rows of distinct packing slots
- [x] Where rows are both distinct in packing slots and dates, the darker green (i.e. distinct days) takes precedence 

In making the changes, a desync bug was spotted:
- When sorting, check that:
- [x] table refetch and dividing line appear at the same time (as opposed to table refetches, THEN dividing line updates a split second after)
- When changing light/dark modes (button on the top right):
- [x] table should NOT refetch
- [x] dividing lines' colour change as required by theme (this is easier to spot with the wider dark green lines)

**Comment by 8kristy** [comment]
Hi @dan-langridge just wanted to clarify the sorting by date bit - do you want the sections to be divided by date only or by date AND slot?

A. Date only (boundaries at the date change, completely ignoring the slot)
![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/42096009/617da7a2-5216-4d08-9a47-dbd25cecf263)

B. Date and slot (dark green boundaries between dates, light green boundaries between slots within each date block)
![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/42096009/47014a2b-7b12-4bfb-9ae5-a6b1592fd7d7)

When sorting by slot it matches your original screenshot (i.e. it's similar to variant A)

Let me know which one of these would be more useful, and if you'd like to have the date separation when sorting by slot, similar to variant B

**Comment by dan-langridge** [comment]
@rickaw Variant B (Date and slot) is perfect, thank you!

**Comment by minalui** [comment]
Looks good - QA passed 🎉

**Comment by dan-langridge** [comment]
Hi all - sorry, I realised I made a mistake above and didn't explain myself very well, so my mistake.
Please can we have the dividing lines (between packing slots and days) on the default sorting on the parcel page?
e.g.
- Load Parcel Page
- parcels are sorted by Date>Shift>Method>Postcode
- Diving lines are shown between dates and packing shifts

**Comment by stonelink** [comment]
Default sorting dividing lines QA'd and verified on Dev

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 2 months, presumed done
