### ISSUE TITLE
Adding Duplicate Collection Centre > Change error message

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#154]
### Describe the solution / feature you'd like

Love that you can't add duplicate collection centres (Names or Abbreviation). But when you do try (just trying to break the system!), the error message is:
"duplicate key value violates unique constraint "collection_centres_acronym_key"Please try again later."

We should remove: "please try again later" as time isn't the issue, but the fact it's a duplicate, so better yet, translate to human language with:

"A Collection Centre with this name/abbreviation has already been added. Please choose a different name/abbreviation"

**Comment by rickaw** [comment]
## Notes for Developers
The `PostgrestError` thrown by the Supabase call contains `code` which we can use to target this specific error. We should display the error message when that particular code is thrown.

**Comment by AmeliaIsCoding** [comment]
### QA:
1. Navigate to admin panel -> add a collection centre
2. Enter the name of a collection centre that already exists and a random acronym
4. Press "create collection centre"
- [ ] Should see error message "A Collection Centre with this name/abbreviation has already been added. Please choose a different name/abbreviation"
5. Repeat, this time enter a random name but an acronym that already exists
- [ ] Should see error message "A Collection Centre with this name/abbreviation has already been added. Please choose a different name/abbreviation"
6. Repeat, this time enter a name and acronym that both already exist
- [ ] Should see error message "A Collection Centre with this name/abbreviation has already been added. Please choose a different name/abbreviation"
7. Repeat, this time enter a random name and random acronym
- [ ] No error message shown
8. Go to the dev supabase and change the name of the collection_centres table to something else - this is to artifically create a database error different to the duplication error
9. Try to create another collection centre with a random name and random acronym
- [ ] Should see an error message that is different from the above (doesn't matter what)
10. Remember to change the name of the collection_centres table back to collection_centres in the dev supabase!

**Comment by rickaw** [comment]
Passed QA 👍
