### ISSUE TITLE
Day/Night Mode too close to Log Out (which doesn't have second step)

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#155]
### Describe the solution / feature you'd like

Log out is quite close to day/night mode, potentially easy to press wrong button and get logged out, considering LogOut doesn't have a second step like a confirmation. Maybe give Log Out a confirmation pop up? (Are you sure you want to log out?) 

Or put Log Out (and potentially a 'Edit Profile' (change name, update email address) settings under in a drop down menu

**Comment by rickaw** [comment]
@dan-langridge Thanks for this. Displaying a pop up is a good idea. If there's a particular appetite for the "Edit Profile" menu, I'm happy to accommodate that further down the line.

**Comment by minalui** [comment]
QA
When logout button is clicked:
[] Modal appears with message "Would you like to log out?" and two buttons - "LogOut" and "Cancel"
[] When clicking outside of the modal, clicking on "x" and clicking on "Cancel" - the modal closes
[] When clicking on "LogOut" - user is logged out and redirected to the login page

**Comment by mtharkins** [comment]
LGTM!
