### ISSUE TITLE
Change Shipping Label Size to 62mm x 150mm (Originally 200mm) to be Eco Friendly

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#156]
### Describe the solution / feature you'd like

We print a lot of labels in the warehouse and they have a lot of white blank space on them currently.
Labels are printed on a continuous spool, so we have the potential of making them shorter (say 150mm) and saving some space, therefore saving labels, and saving money, and the environment. I'm confident we can fit all the necessary info on there still.

**Comment by AmeliaIsCoding** [comment]
### QA
1. Navigate to /parcels
2. Select 1 parcel
3. Actions -> download shipping label -> quantity = 1 -> create pdf -> download pdf -> open the pdf
-[ ] The delivery instructions text should be fully contained within the borders of the shipping label, with the text going onto the row(s) beneath if required
5. On the pdf, click on the 3 vertical dots in the top right hand corner to get document properties of pdf
-[ ] The page size should be 150 x 62 mm (landscape)
6. Repeat for a couple more parcels to check behaviour for different delivery instruction text lengths
-[ ] The delivery instructions text should be fully contained within the borders of the shipping label, with the text going onto the row(s) beneath if required, for different delivery instruction text lengths

**Comment by minalui** [comment]
QA all passed! 😄
