### ISSUE TITLE
Driver Overview PDF - Editable Message by Admin

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#157]
### Describe the solution / feature you'd like

On the Driver Overview PDF, the message "at the end of your shift" would be great to be editable by admin, to update phone numbers etc as staff change.

**Comment by rickaw** [comment]
## Notes for developers
This would involve 
- adding an entry in the `website_data` table with key `driver_overview_message`
- adding a section on the Admins panel, displaying the editable `website_data` table
  - `item` - human-readable representation of the `key` e.g. "Driver Overview PDF Message"
  - `value` - the current value of the item

**Comment by AmeliaIsCoding** [comment]
@rickaw do you want the website_data table in admins panel to contain just the Driver Overview PDF Message or all fields in the website_data table? (currently the only thing in there is the message at the top of lists page, which is also editable on the lists page itself)

**Comment by rickaw** [comment]
> @rickaw do you want the website_data table in admins panel to contain just the Driver Overview PDF Message or all fields in the website_data table? (currently the only thing in there is the message at the top of lists page, which is also editable on the lists page itself)

@AmeliaIsCoding Good question, I think displaying all fields makes sense and improves visibility for admins :)

**Comment by dan-langridge** [comment]
Just Driver Overview message please, thank youOn 20 Mar 2024, at 15:06, AmeliaIsCoding ***@***.***> wrote:﻿
@rickaw do you want the website_data table in admins panel to contain just the Driver Overview PDF Message or all fields in the website_data table? (currently the only thing in there is the message at the top of lists page, which is also editable on the lists page itself)

**Comment by dan-langridge** [comment]
That’s fine with me too, as long as we keep the functionality for the message on Lists to be edited on the lists page (‘Manager’s’ are allowed to edit this message. Only ‘Admin’ allowed to edit Driver Overview message)On 20 Mar 2024, at 16:15, Ricky Kawagishi ***@***.***> wrote:﻿

@rickaw do you want the website_data table in admins panel to contain just the Driver Overview PDF Message or all fields in the website_data table? (currently the only thing in there is the message at the top of lists page, which is also editable on the lists page itself)

@AmeliaIsCoding Good question, I think displaying all fields makes sense and improves visibility for admins :)

**Comment by rickaw** [comment]
@dan-langridge Sure, we'll keep the editing functionality on the lists page and display all editable data in the admins panel too! Thanks

**Comment by AmeliaIsCoding** [comment]
### QA
(thanks Mina for these QA instructions which I mostly stole from VFB-117)

On dev website login as admin user, navigate to admin panel

Acceptance criteria

- [ ] Edit Website Data should appear as a panel on admin page
- [ ] On clicking ‘edit website data’ the panel should expand to display a table with headers "Field" and "Value". There should be 2 rows, Lists Text and Driver Overview Message
- [ ] On clicking ‘edit’ button (pencil), will make the value cell editable. 
- [ ] The focus should automatically change to the value cell, with the caret at the end of the text.
- [ ] When typing in the cell, pressing enter creates a new line, but does not save/stop editing the cell.
- [ ] On saving an edited row, the changes are reflected on the table in the front end
- [ ] On clicking 'x' on a row edit, the changes should be reverted and row is not changed
- [ ] On editing the Driver Overview Message and saving it, the downloaded driver overview PDF from parcels page (in actions) should contain the new message at the top
- [ ] On editing the Lists Text and saving it, the lists text at the top of the lists page should display the new text
