### ISSUE TITLE
Creating Driver Overview PDF - Please default date to 'today'

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#158]
### Reproduction steps

When you create a driver overview PDF it asks for the date. 

### Expected behaviour

When you create a driver overview PDF, Please let it default to todays date

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by AmeliaIsCoding** [comment]
### QA
1. Navigate to /parcels
2. Select a parcel
3. Actions -> download driver overview
- [ ] the date selector should be defaulted to today
4. Create pdf -> download pdf -> open the pdf
- [ ] the date in the pdf should correspond to today

**Comment by mtharkins** [comment]
LGTM!
