### ISSUE TITLE
Attempting to print duplicate 'Shipping Labels' or 'Shopping List' needs a warning message

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#159]
### Describe the solution / feature you'd like

If printing Labels or Shopping list for a second time, a warning message needs to appear before the action is run: 
	“The following postcodes have already been printed: E3 2AB. Are you sure you want to print again?”

**Comment by AmeliaIsCoding** [comment]
Notes for devs:
I think this best solution will be to check the last status of the selected parcel, and if it is Shipping Labels Downloaded / Shopping List Downloaded, display the warning message.

**Comment by maxjohns0n** [comment]
> Notes for devs: I think this best solution will be to check the last status of the selected parcel, and if it is Shipping Labels Downloaded / Shopping List Downloaded, display the warning message.

We agreed to instead check the `events` table to see if the parcel has ever had any Shipping Labels Downloaded / Shopping List Downloaded events. This is in case there has been one but it isn't the most recent event for that parcel.

**Comment by maxjohns0n** [comment]
### QA

- Download some shipping labels for a couple of parcels with different postcodes
- [x] When trying to download again, a warning should appear in the modal
- [x] The postcodes of the parcels you already downloaded should be listed
- [x] Any parcels selected which don't already have any labels downloaded should not be listed
- [x] When no parcels with labels downloaded are selected, the warning doesn't appear
- [x] Postcodes should not be duplicated in the warning message, even if there are multiple parcels selected with that postcode
- [x] Repeat for shopping list downloads

**Comment by KylePUG** [comment]
QA passed!

I do wonder though if more specificity is needed, e.g. when a lot of parcels with the same postcode is downloaded but only one of them has been downloaded before - it will be quite hard to figure out which it is if it isn't displayed in "Last Status". Maybe an optional 'more info' dropdown in the warning message that lists the parcels already downloaded or the number of parcels that are already downloaded for each postcode? Possibly something for another ticket though.

Anyway, this seems to do what's required so well done! :)

**Comment by maxjohns0n** [comment]
> I do wonder though if more specificity is needed, e.g. when a lot of parcels with the same postcode is downloaded but only one of them has been downloaded before - it will be quite hard to figure out which it is if it isn't displayed in "Last Status". Maybe an optional 'more info' dropdown in the warning message that lists the parcels already downloaded or the number of parcels that are already downloaded for each postcode? Possibly something for another ticket though.


Yeah I agree it could get confusing. Probably something we'd want to discuss with Dan and make a new ticket for if needed.

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 2 months, presumed done
