### ISSUE TITLE
2 Factor Authentication

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#161]
### What is your question?

Do we need 2 Factor Authentication when logging in?

**Comment by rickaw** [comment]
@dan-langridge We don't require 2FA from users at the moment. It is certainly something we could look into if there's an appetite for it. Is there a particular concern?

---

We are also considering an invite-link as a possible approach when signing up users as an admin (nothing set in stone yet). Here's is how it could work:
- An admin uses the admin panel to enter the email address for a new user e.g. new volunteer
- The new vulunteer will receive an invite link to sign up
- The new user will be given the lowest permission by default (in our case the "Volunteer" role)
- Admins can change the role of each user if required

To achieve this, we'll need to implement the invite-link flow as well as adding the capability on the admins page to edit user roles.

**Comment by dan-langridge** [comment]
This works for me. 2FA was mentioned by Elizabeth but we can think about later.

Currently, I email new users an introduction to the app email with instructions how to log in, links to training videos, a policy document they need to read etc. If that can be part of the email the user receives that would be super. below info would obviously need to be updated for new app, but to show what happens currently...

Hi [User]

Welcome to the Lambeth FoodBank app.

Below are links to all the instructional videos and PDFs. 
Please watch the video and read the PDF’s, and then you should be ready to go, it’s as easy as that. 

If you are going to be using an iPad, I have also included the iPad instructions.

Please also read the attached IT policy document.

--------------------------------------------------------

FoodBank App: https://foodbank-app.christchurchlondon.org <https://foodbank-app.christchurchlondon.org/>

Your username is:xxxxxxx
Your password is: xxxxxxx

--------------------------------------------------------

When you first log in you will be prompted to change your password to something personal and memorable to you. Keep your password safe.

** It is sometimes easier to use the FoodBank App on a different web browser to the one you use normally. 
For example; use Google Chrome for the FoodBank App and use Microsoft Edge for your daily use. ** 

** When attempting to log in, you may see a Permission Denied page. If this happens, Go to google.com <http://google.com/> / gmail and sign out of any accounts you are logged into and then try again. If that doesn’t work, use the FoodBank App in a Private Browsing Window. If you are not sure how to do that, google your web browser and Private Browsing Window. (e.g google: Chrome Private Browsing Window), or follow the PDF guide below on trouble logging in, and if that fails, send me an email and I’ll see if I can help. It’s sometimes best to use the app in a Private Browsing window on your browser. **

Having trouble logging in?

- Close all tabs
- Go to google.com <http://google.com/>
- Sign out of any accounts you are logged into (press the circular icon top right, and press sign out)
- Go to the FoodBank App Website. Here is the link.
https://foodbank-app.christchurchlondon.org <https://foodbank-app.christchurchlondon.org/> 
- Log in using ***@***.*** ***@***.***> username above
- Enter your password (above)

**This is not an email address. You do not have an email account associated with this account. This is solely a username for you to log into the app.**

--------------------------------------------------------

FoodBank App
https://foodbank-app.christchurchlondon.org <https://foodbank-app.christchurchlondon.org/>

Full Instructional Video
https://christchurchlondon.box.com/s/d6rd2z6h04kxz3qx4txwk6bb694721rv

Using the FoodBank App - PDF
https://christchurchlondon.box.com/s/ks4kbv4twllieoxrgo7mdrti19dsv0fl

Using an iPad - PDF
https://christchurchlondon.box.com/s/63k80rtytn19tzf9gu3j9y6yxo1rpbte

Having Trouble Logging in? Read this.
https://christchurchlondon.box.com/s/eoapmscvyustoy9vwdx4s2rb5go7r2os

--------------------------------------------------------

If you have any questions, please ask.

Thanks
Dan
***@***.*** ***@***.***>

**Comment by rickaw** [comment]
@dan-langridge Thanks for sending the current sign-up email, this will form the basis of the invite email if we decide to go with the invite-link approach!

Closing this issue for now - feel free to reopen it if there's further questions.
