### ISSUE TITLE
Bring Back functionality to "Download Shipping Labels for Multiple Clients" 

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#176]
### Describe the solution / feature you'd like

Used to be able to:
- Select Multiple Clients
- Print Shipping Labels
Now get an error that says: "Please select exactly one parcel."
In Warehouse, quite common for 2 or 3 parcels to get packed at the same time which all need "3" labels, so batch printing is helpful.

PDF would look like:
Postcode ABC Label 1 of 3
Postcode ABC Label 2 of 3
Postcode ABC Label 3 of 3
Postcode XYZ Label 1 of 3
Postcode XYZ Label 2 of 3
Postcode XYZ Label 3 of 3

**Comment by minalui** [comment]
QA
As a user, when I select multiple parcels and click on generate shipping labels
- [ ] A pdf file is generated with all the parcels selected and in the quantity specified
- [ ] Each label shows label ... of ...

**Comment by AmeliaIsCoding** [comment]
QA passed :)
