### ISSUE TITLE
Can't Add a Parcel with Today's Date

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#178]
### Reproduction steps

When I (at 2:42pm)
- Add New Parcel for Client
- Select Date as Today
- Error: "Please enter a date in the future"

### Expected behaviour

We should be able to add parcels to todays date

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by AmeliaIsCoding** [comment]
### QA:
Add New Parcel for Client
Select Date as Today
- [ ] No error message
Fill out other fields and click submit
- [ ] No error message, parcel submitted successfully
Add New Parcel for Client
Try to select date as yesterday
- [ ] Not possible
