### ISSUE TITLE
On Parcels Page: Instead of Status showing "None" can it be a blank field?

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#179]
### Describe the solution / feature you'd like

- On Parcels Page
- A Blank Status show "None"
- can it instead be a blank field?
- Helps user to scan app for Clients that need attention, cleans up the visuals

**Comment by minalui** [comment]
QA
As a user, when I view parcels with a null status in parcels table
- [ ] The parcel status displays a blank field instead of None

**Comment by AmeliaIsCoding** [comment]
QA passed :)
