### ISSUE TITLE
Driver Overview PDF - Not Creating a Status

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#180]
### Reproduction steps

When I:

- Select Multiple Clients
- Download Driver Overview PDF
- Submit
- Status of Clients does not update

### Expected behaviour

Status of Clients should update to:
Out for Delivery with [Name of Driver] [Date]

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by rickaw** [comment]
## Developer Notes
- [VFB-175](https://softwiretech.atlassian.net/browse/VFB-175) covered the creation of a new status
- The outstanding task is to change the new status name from `Driver Overview Downloaded` to `Out for Delivery with [Name of Driver] [Date]`

**Comment by AmeliaIsCoding** [comment]
Notes: 
-Delete driver overview downloaded status as this is no longer needed
-When driver overview downloaded, new status should be "Out for Delivery" with the event data containing the driver name and date

**Comment by AmeliaIsCoding** [comment]
### QA

- Select a parcel with its last status in the past
- Download the driver overview for the parcel, inputting a driver name and a date of your choice
- [x]  The parcel's status should update to Out for Delivery (with [Name of Driver]) @ [DD/MM/YYYY] where the name and date are correct to what you input
- [x] In the parcel modal, in the events table, the most recent event should display be Out for Delivery (with [Name of Driver]) @ [DD/MM/YYYY]
- [x] Repeat but enter the driver name "     John     " --> the driver name in the both the status and the PDF should be "John", ie with whitespace trimmed
- [x] "Driver Overview Downloaded" is not visible as a status in the front end
- [x] No events in the `events` in supabase have event name "Driver Overview Downloaded"
- [x] In the `status_order` table, there is no row with status "Driver Overview Downloaded"
- [x] In local, some seeded parcels are shown in the front end with last status "Out for Delivery (with [Name of Driver]) @ [DD/MM/YYYY]

**Comment by rickaw** [comment]
@dan-langridge In the parcels table's "last status" column, we currently show the name of the last status along with the date the status was set (see image). We also allow the user to specify the delivery date when they download the driver overview, which goes on the driver overview PDF, but this date is not stored for any other purposes yet.

Now, if we update the status to the `Out for Delivery with [Name of Driver] [Date]` format, it'd make sense to display the delivery date, not the date the PDF was downloaded.. This leads to a slightly inconsistent use of the date in the last status column. Would you rather keep the wording `Driver Overview Downloaded` with the date the PDF was downloaded, or change to `Out for Delivery with [Name of Driver]` with the the delivery date? The change would require some additional work, but happy to accommodate.


![Image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/114006382/f7917e3a-b612-410c-b6e0-d00142111abc)

**Comment by dan-langridge** [comment]
Please can we go with

Out for Delivery with [DriverName] [DeliveryDate]

**Comment by kaydentsoftwire** [comment]
QA passed

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 3 months, presumed done
