### ISSUE TITLE
Driver Overview PDF - Driver Name should be Mandatory Field

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#181]
### Reproduction steps

Select Multiple Clients
Download Driver Overview PDF
Leave Driver Name Blank
Submit
Success

### Expected behaviour

Driver Name should be Mandatory Field so we can track who has the parcel

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by maxjohns0n** [comment]
### QA

- Navigate to parcels page
- Select one or more parcels in the table
- From "Actions", choose "Download driver overview"
- [ ] "Download PDF" button is displayed as being disabled
- [ ] Can't click on the button/it doesn't do anything
- Enter some text into the Driver's Name field
- [ ] Button shows as enabled
- [ ] Clicking the button submits the form and generates a correct PDF
- [ ] Deleting all the text from the Driver's Name field disables the button again
