### ISSUE TITLE
Family Size not Calculating Correctly /Not Saving updated info

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#183]
### Reproduction steps

Using client 'Marcelle Ziemann' as an example:
When I:
- Open Clients Page
- Open Client Modal
- Edit Client Details
- Change Adults to 2 Female,1 Male, 0 Kids
- Submit
Household on Modal is shown as Family of 8 Occupants (4 adults, 4 children)
Family Size information is not saving.
- Edit Client Details again
- Old Data is Shown

### Expected behaviour

Edit Client
Change Family Size (Number of Male and female Adults, number of children
Submit
Information is updated on Client Modal, and on Parcels page so that correct shopping list is generated

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by AmeliaIsCoding** [comment]
### QA: 
Open Clients Page
Find client "Marcelle Ziemann"
Open Client Modal
Edit Client Details
Change Adults to 2 Female,1 Male, 0 Kids
Submit
- [ ] Check the family details shown in the modal and the table are correct to what you just submitted
Edit Client Details again
- [ ] Check the updated behaviour is shown
Repeat for a few different clients and combinations of family makeup
- [ ] Family details save correctly every time

**Comment by rickaw** [comment]
QA Passed :)
