### ISSUE TITLE
Change text "Item" to "Parcel" on Shipping Label

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#184]
### Describe the solution / feature you'd like

On the Shipping Label, where it says "Item 1 of 2" , please change the word "Item" to "Parcel".

An 'Item' in the warehouse is more like a tin of beans

**Comment by kaydentsoftwire** [comment]
I've been assigned to this but the shipping label - below - seems to say Label 1 of 1 (rather than Item or Parcel) - should I change it to Parcel?


![Image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167894215/9436a69c-ccd1-4da8-91f2-71530b1399c1)

**Comment by kaydentsoftwire** [comment]
QA steps:
- login to site
- go to parcels page
- select a parcel, click actions and 'download shipping labels'
- shipping label should should 'Parcel 1 of 1' in bottom right hand corner

**Comment by AmeliaIsCoding** [comment]
QA passed, although text is now even closer to the edge, but this will be dealt with in [VFB-213](https://softwiretech.atlassian.net/jira/software/c/projects/VFB/boards/862?selectedIssue=VFB-213)
