### ISSUE TITLE
on Driver Overview PDF - add column for number of Parcels per client

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#185]
### Describe the solution / feature you'd like

on the Driver Overview PDF, please add a column to show the number of Parcels for that client.

**Comment by rickaw** [comment]
@dan-langridge The driver overview PDF's table displays one row per parcel that has been selected. e.g. If we have selected three parcels for the same client and created the driver overview PDF, three rows are displayed (see image). Would we still want to add a column to show the number of parcels for that client? Or do we want to show one row per client, and add a column to show the number of parcels for that client? (In this case, should the "Packing Date" column display the packing dates of all the parcels for that client?)


![Image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/114006382/cc56fba3-a27a-47ac-a1e1-ae20cd15a570)

**Comment by dan-langridge** [comment]
Sorry some miscommunication comes from using the word Parcels in 2 different places, our fault...
The column i'd like to add is the number of labels printed for that parcel. (So in this scenario, Aaliyah Johnston, we printed 10 Labels, so a column to show 10, so the driver knows this delivery has 10 parcels/boxes/bags associated with it.

**Comment by rickaw** [comment]
@dan-langridge Ah that makes sense, thanks for clarifying!

**Comment by rickaw** [comment]
## Developer Notes
- For each parcel to display on the driver overview, get the latest `Shipping Labels Downloaded` event associated with that parcel and retrieve the number of shipping labels downloaded which is stored in the `event_data` field.
- Add "Number of parcels" column in the Driver Overview PDF which displays the number of shipping labels for that particular parcel.

**Comment by maxjohns0n** [comment]
### QA

- On the parcels page, download some shipping labels for some parcels
- Download the driver overview for those parcels
- [x] PDF has "Number of parcels" column
- [x] Parcels which you downloaded labels for have the correct number in the column
- [x] Parcels which haven't had any labels downloaded show as "No labels downloaded"
- Go back and download a different number of labels for a parcel
- Download a new driver overview
- [x] The new PDF has the updated number of labels (i.e. the most recent value)

**Comment by kaydentsoftwire** [comment]
QA passed
