### ISSUE TITLE
Client Page - Add Search by Postcode + Phone Number

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#187]
### Describe the solution / feature you'd like

On the Client page, please add the ability to search by postcode and phone number

**Comment by KylePUG** [comment]
QA:

- Login and navigate to the "Clients" page
- [ ] "Phone" column should be displayed
- [ ] Filter for "Phone" added
- [ ] Filter for "Postcode" added
- Filter for "Postcode" should
  - [ ] Allow lowercase search
  - [ ] Allow search for "NFA" (including lowercase search i.e. "nfa")

In this ticket the filter functions have also been generalised, i.e. 
- [ ] phone, postcode, and fullname searches should be equivalent in both Parcels and Clients pages

**Comment by Alex-Softwire** [comment]
QA:
✅- Phone and Postcode filter added
✅ - Phone and postcode filter work and filter (the postcode filter works on the parcels page too!)
✅ - Postcode filter includes lowercase which is nice.

-> Would be nice if the postcode filter was ambivalent to adding spaces e.g CB244RT vs CB24 4RT. Quite often postcodes in forms require the former. Would also be nice if there was a filter in the clients form to enforce a certain type (either with spaces or without), or if not a conversion between the two. Cause it might end up that some clients enter their postcode without a space and some with, which could cause confusion. Probably a job for a 2nd ticket so might raise with the general chat. 

-> How does the country code system work? Does it automatically append +44 if you write 07..... into the phone number. It won't let you search for phones in non country code format? Again, not sure if this matters but probably a 2nd ticket.

-> Backslashes don't count as a character for some reason, doesn't matter but a funny observation.

Let me know what you think about the 1st two points, and whether I should raise with the general vfb chat. Happy to move this ticket to done, if the other points are not important/ are separate tickets. Good work adding the filter (and commonising the postcode filter code)!

**Comment by KylePUG** [comment]
1. This is a good point. I agree with you in both cases. Having a conversion between the two sounds like a good idea for sure! I do know that Kay is currently working on a ticket that (most likely) takes in only 1 of the two (with spaces) so this could be quite important. Please do raise it :)
2. I believe that when inputting the phone number into the client form it does automatically to the +44 format regardless of whether it starts with +44 or 07. There isn't a similar thing when filtering though - so maybe that is worth raising as well!

Thanks for a great QA!

**Comment by Alex-Softwire** [comment]
Have asked on the chat about whether to fix 1 & 2 :)

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 3 months, presumed done
