### ISSUE TITLE
Client Postcode - Amend Response Validation to allow "NFA"

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#188]
### Reproduction steps

When I:
- Add a new client who is homeless and doesn't have an address, I give them the postcode NFA (No Fixed Abode)
- Error : Please enter a valid entry.

### Expected behaviour

A client who is homeless and doesn't have an address, in the address field we would just give them the postcode NFA (No Fixed Abode). This is always for clients who are collecting their parcel from a Collection Centre.

I see 2 solutions:

Easy) Change/Remove the Response Validation for Postcode to allow for free text (NFA)

Less Easy) Add a tick button to say "No Address" which then removes the address fields and automatically adds 'NFA' onto the app, and shopping list, shipping label, driver overview etc.

We are aware that using NFA as a postcode breaks the "Generate Map" feature but it's something we know and know not to do....

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by rickaw** [comment]
## Developer Notes
Seems like the best course of action would be to:
- Make the postcode nullable in the db (if it isn't already)
- Add a "No address" checkbox next to the address field on the form
  - When the checkbox is ticked, the address field should be disabled, and the value set to null
- In pages that use the postcode (shopping list, shipping label, driver overview etc), display "NFA" whenever the postcode is null
- For generating the map, ignore null postcodes.
- Change the generated seed data so that some clients have a null postcode.

**Comment by AmeliaIsCoding** [comment]
Ricky's above notes was the approach I used

Also note:

-when a client has null postcode, their entire address is displayed as "NFA", so the other address fields are ignored even if populated
-in the client add/edit form, ticking the checkbox hides the address field, not just disabling. the address fields are all set to an empty string or null (postcode)
-if a client with null postcode is edited, the other address fields are set to an empty string on submitting the edit form (unless they are edited by the user). They appear empty in the form during the editing process.

**Comment by AmeliaIsCoding** [comment]
### QA

- [ ]  In parcels page, some parcels are shown with postcode equal to NFA
- [ ] On opening the parcels modal, the entire address of such parcels is shown only as NFA
- [ ] Select a parcel with NFA -> create shipping label -> the postcode is shown as NFA -> download PDF -> the entire address is shown only as NFA in the PDF
- [ ] Repeat for shopping list action
- [ ] Repeat for driver overview action
- [ ] Repeat for day overview action, you will need to find a date on which parcels with NFA will be collected. (I suggest trial and error)
- [ ] Select a parcel with NFA -> generate map -> an error should be displayed in the action modal
- [ ] Select a parcel with NFA and a parcel with an address -> generate map -> the link should open, with only the parcel with the address included as a destination
- [ ] In clients page, some clients are shown with postcode equal to NFA
- [ ] On opening the clients modal, the entire address of such clients is shown as NFA
- [ ] On adding a client, we can tick the No Address checkbox, and the client is added with address shown as NFA
- [ ] On editing a client with an address, we can tick the No Address checkbox, and the client's address is updated to show as NFA
- [ ] On editing a client with no address, we can untick the No Address checkbox. Trying to submit with the postcode and/or address line 1 left as empty displays an error. Filling these fields in then submitting works as usual. The client's address is updated accordingly and displayed with the information, no longer as NFA

**Comment by minalui** [comment]
QA passed 🎉
