### ISSUE TITLE
Add date+time stamp of when parcel added to a client (separate to packing date)

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#191]
### Describe the solution / feature you'd like

When I open the client modal to see the history of the parcels that client has received, it would be helpful to see a date and timestamp of when the parcel was originally added for that client.

This is different to the Packing Date, as the parcel could get moved to a few different dates on the app during the lifecycle of that parcel, but it's helpful to know when it was originally entered.

example: life cycle of a chaotic parcel
10th - Added to App for 11th packing shift
11th - Called, can't receive delivery today, move to 12th
12th - attempted delivery, not home, called, will be home tomorrow, move to 13th
13th - another failed delivery, called, moved to 15th
15th - successful delivery

In the current app, we wouldnt know when that parcel was added originally to the app.

**Comment by rickaw** [comment]
## Developer Notes
- Add `created_at` field in the parcels table, to be set to the current time when a parcel is inserted automatically
- Make necessary chanegs to display the timestamp in the following places
  - on the parcels table as an additional column
  - on the parcel detail modal as an additional field "Created at"
- In the generated seed data, manually set this to noon on 31 Dec 2023 (this is before all parcel events) so it visually makes sense

**Comment by minalui** [comment]
QA passed 👍
