### ISSUE TITLE
Create a New Page called "Info" (Noticeboard for app users)

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#192]
### Describe the solution / feature you'd like

It would be helpful to have a new page on the app called "Info".

This would be like a Wiki/noticeboard page, with up to date information from the managers for callers, other app users, with information like how-to instructions, notes for callers etc.

Can be just a plan text box where text and links can written.

Editable by: 'admin' (and 'Managers' if possible)
Viewable by: 'all'

**Comment by rickaw** [comment]
@dan-langridge Interesting - On this Info page, I'm visualising multiple sections, each with some text / links (see image for an example). Is this the kind of thing you'd like?

![Image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/114006382/672ca559-034c-40d7-9d8e-54dd28156de5)

**Comment by dan-langridge** [comment]
Yeah perfect, I love that. The ability to change the name of the Sections, add and remove sections as required would be very cool.

Thanks
Dan

**Comment by rickaw** [comment]
## Developer Notes
- Create a `wiki` table in the database with two text fields `title` and `content`. This table can be read by any authenticated users, but can only written to by admins and managers (if the manager role has been added by [VFB-131](https://softwiretech.atlassian.net/browse/VFB-131))
- Create a page `/wiki` that fetches the new table and displays it using accordions (MUI accordion should do)
- On the Admins page, add "Manage wiki data" section to allow admins to add / remove / edit wiki entries

**Comment by Stuart-Knowles-SW** [comment]
@dan-langridge Can I double check what the ideal version of this looks like. Do we want something like a wiki, with static information that can be updated by admins/managers, or a noticeboard with short-lived posts for news and temporary updates?

Or if you want we can actually have both as separate pages

**Comment by dan-langridge** [comment]
A wiki page would be ideal thank you

**Comment by Stuart-Knowles-SW** [comment]
Great! It looks like the current pattern for how admins/managers edit things is via the "Admin" page. It feels more natural for this to be edited in-place, i.e., admins and manager will have little "edit" buttons on the various entries in the wiki. Does that sound good or would you prefer to keep it consistent and have everything edited by the Admin page?

**Comment by dan-langridge** [comment]
I would like mangers to edit this page as well, so having edit button on the Info page makes sense to me! ( as manager can’t see admin page)Kind RegardsDan Langridge(+44) 07540 696683On 1 Jul 2024, at 11:15, Stuart Knowles ***@***.***> wrote:﻿
Great! It looks like the current pattern for how admins/managers edit things is via the "Admin" page. It feels more natural for this to be edited in-place, i.e., admins and manager will have little "edit" buttons on the various entries in the wiki. Does that sound good or would you prefer to keep it consistent and have everything edited by the Admin page?

**Comment by dan-langridge** [comment]
I'm happy with where this feature is and happy to mark it as done.
