### ISSUE TITLE
On Driver Overview PDF - Indicate which parcels are 'Collection' and which parcels are 'Deliveries'

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#196]
### Describe the solution / feature you'd like

If one of our drivers is taking all the Collections parcels AND doing some deliveries, the Driver Overview PDF that is created for them does not show which parcels are collections and which are deliveries, so might home deliver a parcel that was supposed to be dropped off at a Collection Centre.

On Driver Overview PDF, can we Indicate which parcels are 'Collections' and which parcels are 'Deliveries'.

Group Collections and mark them with the name of the collection centre and the Feet Icon. 
Group Deliveries and mark them the Van Icon.

**Comment by kaydentsoftwire** [comment]
QA steps:
Note that the postcode sorting should match javascript default sorting (with E8 coming before E24, for example), which reflects how the sorting works elsewhere
- go to parcels page and select some parcels for collection and some for delivery
- under actions, click 'Download Driver Overview'
- [x] a pdf with two tables should appear
- [x] Deliveries should have a van icon next to it and collections should have a footprints icon next to it
- [x] The collections table should have a column 'Collection Centre'
- [x] The deliveries table should have an 'Address' column
- [x] The deliveries should match what was labelled as delivery, and the collections should match what was labelled as collections
- [x] Deliveries should be ordered by postcode
- [x] Collections should be ordered by collection centre
- go to parcels page and select just deliveries then download driver overview
- [x] only the deliveries table should appear, with deliveries ordered by postcode 
- go to parcels page and select just collections then download driver overview
- [x] only the collections table should appear, with collections grouped/ordered by collection centre

Error testing - to be done on local.
- go to parcels table in the database
- look at the client in your top row and search for them in the parcel table
- select their parcel and click 'Download driver overview'
- when the modal is up, delete the collection centre for the parcel in the database (just the id in the parcel's row, not the whole collection centre)
- click Download PDF on the modal
- [x] you should see the error, "Failed to find a collection centre for one or more of the parcels. LogId:" + log ID

**Comment by minalui** [comment]
QA passed! 🎉

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 3 months, presumed done
