### ISSUE TITLE
Parcels Page - Show # total of how many parcels have beens selected

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#197]
### Describe the solution / feature you'd like

When selecting parcels, show somewhere on the screen how many parcels have been selected

<img width="1624" alt="Screenshot 2024-03-26 at 15 05 32" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/80202270/f6448ddc-97c9-4688-ab48-5b6094f9d9b9">

**Comment by rickaw** [comment]
QA
- [ ] When you have not selected any parcels on the parcels table, no text is shown next to Action & Status buttons
- [ ] When you have selected one parcel, "1 parcel selected" is displayed
- [ ] When you have selected multiple parcels, "X parcels selected" is displayed
- [ ] When you tick the "All" checkbox, "X parcels selected" is correct (compare with the total count at the bottom right of the table)
