### ISSUE TITLE
Improve the password reset flow

### ISSUE THREAD

**Issue by rickaw** [NorwoodAndBrixtonFoodbank/nbf-website#199]
### Describe the solution / feature you'd like

- Edit the password reset email to say that the link needs to be opened using the same machine and browser
- If the password reset link did not work as expected, we should display an error and explain that it did not succeed, and a likely reason why.
- If password reset is successful, direct user to / which should redirect to parcels page automatically (as the user is already signed in at this point)

Raised by #177

**Comment by rickaw** [comment]
QA Steps
- [ ] Password reset email mentions that the link needs to be opened using the same machine and browser
- [ ] When password reset is successful, direct user to / which should redirect to parcels page automatically (as the user is already signed in at this point)
- [ ] If you click the same link twice, an error is displayed and explains that it did not succeed and a likely reason why.

**Comment by minalui** [comment]
QA passed
