### ISSUE TITLE
Day Overview PDF - Option to Select All Options (Delivery and All Collection Sites)

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#202]
### Describe the solution / feature you'd like

On the day Day Overview PDF, it would be good to have the option to Select All Options (Delivery and All Collection Sites)

<img width="1306" alt="Screenshot 2024-03-26 at 16 30 05" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/80202270/6cb26564-4e4f-4ad3-99a3-751c276375d2">

**Comment by dan-langridge** [comment]
‘All' would be the default use case for us

I like the idea of checkboxes, so if we go with that, we could have, by default, all Methods are selected, and the user can deselect any method as required?

**Comment by rickaw** [comment]
> ‘All' would be the default use case for us I like the idea of checkboxes, so if we go with that, we could have, by default, all Methods are selected, and the user can deselect any method as required?

Sounds like a good idea. Thanks for confirming!

**Comment by dan-langridge** [comment]
#222 Resolves this

**Comment by rickaw** [comment]
Closing this as it will be resolved by #222
