### ISSUE TITLE
Day Overview PDF - on modal - Rename 'Location' to 'Method'

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#203]
### Describe the solution / feature you'd like

On the Day Overview PDF modal - Rename 'Location' to 'Method'

<img width="1224" alt="Screenshot 2024-03-26 at 16 33 03" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/80202270/397330b9-2e2a-48a7-810a-d0d8d38b0033">

**Comment by rickaw** [comment]
This will be resolved by #222

**Comment by rickaw** [comment]
Closing this as it will be resolved by #222
