### ISSUE TITLE
Parcel Form - Voucher Number should not be required

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#204]
### Reproduction steps

When I:

- Add New Parcel
- Try and leave the voucher number entry blank
- "This field is required"

### Expected behaviour

Not all parcels have a voucher number, so this field should not be required.

<img width="1281" alt="Screenshot 2024-03-26 at 16 38 57" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/80202270/8281c022-68b4-4dae-90f9-fb45920f97eb">

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by rickaw** [comment]
## QA
Given I have opened a client detail modal and clicked "Add parcel"
When I submit a parcel with the voucher number left empty
Then the parcel is added successfully

Given I have opened a client detail modal and clicked "Add parcel"
When I add some text to the voucher number and then remove the text to be empty
and submit a parcel with the voucher number left empty
Then the parcel is added successfully

Given I have opened a client detail modal and clicked "Add parcel"
When I add some text to the voucher number and submit a parcel
Then the parcel is added successfully

Given I have opened a parcel detail modal which has a voucher number
When I edit the parcel and remove the voucher number and submit
Then the parcel is saved successfully

**Comment by minalui** [comment]
QA passed!
