### ISSUE TITLE
Default Parcel Page Sorting (Date>Shift>Method>Postcode)

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#206]
### Describe the solution / feature you'd like

By default when you load the Parcels page, the parcels should in the following order:

1. Date
2. Packing Shift (AM/PM/Shift1,2,3,4)
3. Method (Delivery, then Collection)
4. Postcode

So that:
The AM Shift is at the top of the page, with deliveries first (sorted by postcode) and collections second (sorted by postcode)

Then PM list has deliveries first (sorted by postcode) and collections second (sorted by postcode)

e.g.
<img width="626" alt="Screenshot 2024-03-26 at 17 11 24" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/80202270/bd0eae65-bd1f-4b6a-8646-a765c02e21f9">

This can then be overridden by user sorting. But default loading of page should be the above.

**Comment by AmeliaIsCoding** [comment]
Notes for devs:

This should also be the sorting behaviour on sorting by the packing date column.

**Comment by kaydentsoftwire** [comment]
QA steps:
**A note that sorting by postcode uses default sorting, and therefore postcodes beginning E24, for example, will appear before postcodes using E8**
- go to admin / collections centre table, and change 'Clapham Collection Centre' to 'Lapham Collection', changing the first letter of the acronym to 'L', as well. 
- navigate to the parcels page
- [ ] You should see the most recent date, with AM Shift at the top of the page, with deliveries first (sorted by postcode) and collections second (sorted by postcode). If these shifts don't have both delivery/collection or there are not both AM/PM on that date, expand the date range to check this
- [ ] Then PM list has deliveries first (sorted by postcode) and collections second (sorted by postcode), followed by any of Shift 1/2 (in number order (see above for example)
- Select a date range of at least 2 days
- Click to sort by packing date
- [ ] The date should be the earliest date now, but still retain the order - AM (sorted by postcode) then PM (sorted by postcode)
- Reverse the sorting
- [ ] The sorting should return to the same as the default state, with delivery always appearing first, regardless of which way it is ordered

**Comment by kaydentsoftwire** [comment]
Is there a specific way the postcodes should be ordered? Is it useful if it goes, for example,
E1, E12, E2, E23, E3
or should it be in the order
E1, E2, E12, E23, E3
with the same structure replicated in the second half of the postcode?

**Comment by 8kristy** [comment]
Hi @dan-langridge just to follow up on Kay's question above - do you have a preference on the order of the postcodes after they get sorted? The default sort that we're using now is just alphabetical, e.g. this list 
```
["E2 6AA", "E24 6AA", "E8 6AA", "E2 62AA", "E2 6AA", "E2 8AA"]
``` 
gets sorted as 
```
['E2 62AA', 'E2 6AA', 'E2 6AA', 'E2 8AA', 'E24 6AA', 'E8 6AA']
```

Which still groups the postcodes together (i.e. all the postcodes starting with `XY12` would sit together, and for the same group, the second part of the postcode would also be grouped, e.g. all `XY12 3zz` would be together and sorted by `zz`), however the ordering is a little odd as Kay outlined above.

Just wanted to double check if leaving the sorting like that is ok or if you'd like us to sort it in some specific way 😊

**Comment by dan-langridge** [comment]
Well, Ideally it would sort
E2
E8
E24

However I understand the challenge that may represent so for simplicity i’m happy to leave it as alphabetical if it’s too much of a pain - we know this quirk now and happy to live with it!

**Comment by kaydentsoftwire** [comment]
Now all sorts by collection centre name. QA steps:

QA steps:
A note that sorting by postcode uses default sorting, and therefore postcodes beginning E24, for example, will appear before postcodes using E8

  - go to admin / collections centre table, and change 'Clapham Collection Centre' to 'Lapham Collection', changing the first letter of the acronym to 'L', as well.
  -  navigate to the parcels page
  - [ ] You should see the most recent date, with AM Shift at the top of the page, with deliveries first (sorted by postcode) and collections second (sorted by collection centre). If these shifts don't have both delivery/collection or there are not both AM/PM on that date, expand the date range to check this
   - [ ] Then PM list has deliveries first (sorted by postcode) and collections second (sorted by collection centre), followed by any of Shift 1/2 (in number order (see above for example)
   - Select a date range of at least 2 days
   - Click to sort by packing date
   - [ ] The date should be the earliest date now, but still retain the order - AM (sorted by deliveries by postcode, then collection centre) then PM (sorted by deliveries by postcode, then collection centre)
   - Reverse the sorting
   - [ ] The sorting should return to the same as the default state, with delivery always appearing first, regardless of which way it is ordered

**Comment by Alex-Softwire** [comment]
QA (Nice work with this.. seems to sort as desired):
✅ - The Parcels page sorts by Date, Packing Shift, Method, Postcode as desired!!!
✅ - When sorting by packing date (either forwards or backwards). The rest of the table is sorted by packing shift, method and postcode!
👍 - Method sorts by Delivery, then Collection (not by the different collection locations, or delivery with congestion charges), I think this is intended :)
👍 -  Postcode does indeed sort alphabetically, rather than by letter, number and letters. This is fine and noted in the QA comments :)

❓ - When you sort by any of the other fields, Packing Shift, Method, Postcode, they are no longer sorted secondarily date sorted. I guess I would have expected, if you sort by Client name, it would be sorted in the order Client Name, Date, Packing Shift, Method, Postcode etc.. Or if you sorted by Method, it would sort by Method, Date, Packing Shift, Postcode in that order. Not sure if this is out of scope for the ticket though, lmk if you disagree, or I make a mistake here. 
❓ - Just something I noticed (not necessarily from this ticket). If you sort by postcode, deleted clients appear randomly in the sort, not in the beginning or end. Is that secretly revealing the deleted clients postcode (if it's sandwiched between two CB24 5FD's), or doing something else a bit random. 

Great work though!

**Comment by kaydentsoftwire** [comment]
Thanks Alex!
In this ticket I only looked at the default sorting and the sort by packing date, I didn't look at any of the other sort methods, so arguably they are outside of the scope of the ticket.
I can check with Kristina and see if she'd like that to be added into this ticket or perhaps raised as a separate one :) 

Def agree that the sorting by postcode with deleted clients is an issue if it is indeed revealing their postcode accidentally - regardless it is probably nicer for them to go to the end - and I wonder if that is part of the in progress ticket about how client's data is anonymised. Will check in with Amelia.

**Comment by Alex-Softwire** [comment]
Re the first point. Unsure whether it would be out of scope - like I'd expect the default sorting to apply secondarily when sorting by another column rather than just random, but it definitely didn't say that in the ticket & not explicitly mentioned in Amelia's comment. Am leaning towards saying it's out of scope though it would be nice for a 2nd opinion on whether it is, in scope, good idea for a 2nd ticket, or not important :). 

Re the 2nd point, have discussed this separately & Amelia is looking into it. Seems to only happen with seeded deleted clients, so shouldn't be an issue in prod.

**Comment by kaydentsoftwire** [comment]
Ahhh I see what you mean, yes I agree actually, I think making the default sorting the secondary sorting for other columns is instinctive and within the scope of this ticket. I'll make those changes :)

**Comment by Alex-Softwire** [comment]
Cool! Am happy with that if you are - definitely think it's a feature that should be there. Just didn't want to make you to do extra work unnecessarily

**Comment by kaydentsoftwire** [comment]
QA steps:
- go to parcels page
- select a date range of at least a few days to ensure you have some parcels with overlaps in each column
- Check that the following sort orders are enforced, with only the first (primary sort) reversing when you reverse the sort. For clarity, collections should be sorted by collection centre and deliveries should be sorting by postcodes:
- [ ] **Family category** = family category > packing date > packing slot > delivery/collection > collection centre name > postcode
- [ ] **Full name** = full name > packing date > packing slot > delivery/collection > collection centre name > postcode
- [ ] **Postcode** = postcode > packing date > packing slot > delivery/collection > collection centre name (this one is not that obvious as it is not often that many people would have the same postcode. You may need to make another parcel to check)
- [ ] **Phone number** = phone number > packing date > packing slot > delivery / collection > collection centre name > postcode
- [ ] **Voucher number** = voucher number > packing date > packing slot > delivery / collection > collection centre name > postcode (may need to create two parcels with the same voucher number to check this)
- [ ] **Packing slot** = packing slot > packing date > delivery / collection > collection centre name > postcode
- [ ] **Last status** = last status > packing date > packing slot > delivery / collection > collection centre name > postcode
- [ ] **Created at** = created at > packing date > packing slot > delivery / collection > collection centre name > postcode

To check that consistent sorting is applied throughout:
- create 2 identical parcels with the same client
- [ ] apply various different sorts and ensure that each time the parcels are in the same order

**Comment by 8kristy** [comment]
Moving to UAT for now to test the things that have been implemented but for next release move back to to do/in progress to finish the new changes started here https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/pull/371

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for 2 months, presumed done

**Comment by dan-langridge** [comment]
@stonelink 
Re-opening as the postcode sorting has been noticed to be wrong.

Example 1 issue:
SE1 0..
SE11 4..
SE11 6..
SE1 8...

Should be:
SE1 0..
SE1 8...
SE11 4..
SE11 6..

Example 2 issue:
SW12 0..
SW12 4..
SW16 6..
SW16 8...
SW2 3..
SW4 5...

Should be:
SW2 3..
SW4 5...
SW12 0..
SW12 4..
SW16 6..
SW16 8...

**Comment by dan-langridge** [comment]
<img width="630" alt="Image" src="https://github.com/user-attachments/assets/641a5a5c-8970-487e-b5e3-b5b12220a66a" />

**Comment by stonelink** [comment]
Hi @dan-langridge the postcode ordering is now #666, so I'm moving this original ticket back to Done
