### ISSUE TITLE
Log out button should not be shown on the forgot password page

### ISSUE THREAD

**Issue by rickaw** [NorwoodAndBrixtonFoodbank/nbf-website#208]
### Reproduction steps

- Sign out (if you are signed in)
- Go to forgot password page
- You see that the log out button is still displayed

### Expected behaviour

The log out button should not be displayed on the forgot password page

### Screenshots / Videos

![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/114006382/362d7b3e-a9f5-43e2-813e-b7f208be7d05)

### What browsers are you seeing the problem on?

Chrome

### What OS is your computer running on?

macOS

**Comment by KylePUG** [comment]
##QA

- Navigate to the Login page (sign out if signed in)
- Click on "Forgot your password?" underneath sign in button
[] Logout button no longer appears on the top right of the screen

**Comment by kaydentsoftwire** [comment]
QA passed
