### ISSUE TITLE
When logged in as 'Caller', can't see any Parcels

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#223]
### Reproduction steps

- Log in as Admin
- Go to Parcels Page
- Can see Parcels

- Log in as Caller
- Go to Parcels Page
- Cannot see Parcels

### Expected behaviour

Admin and Caller should both be able to see the Parcels

### Screenshots / Videos

<img width="1869" alt="Screenshot 2024-03-28 at 17 48 31" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/80202270/58c91709-3aa0-4841-8a6b-c06db8837819">
<img width="1873" alt="Screenshot 2024-03-28 at 17 48 02" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/80202270/a789b93c-9cd2-47b9-9a14-c87d596b70e5">

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by rickaw** [comment]
This was fixed as part of [VFB-170](https://softwiretech.atlassian.net/browse/VFB-170)

**Comment by rickaw** [comment]
QA
- [ ] Given I am logged in as an admin, I can see the parcels and clients successfully
- [ ] Given I am logged in as a caller, I can see the parcels and clients successfully

**Comment by minalui** [comment]
QA all passed
