### ISSUE TITLE
Parcels Collection Time Slot - Change from Free Text to Admin chosen time slots for each centre

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#233]
### Describe the solution / feature you'd like

Currently, when adding a Parcel for a collection, the Collection Time Slot is Free Text 

Change this to:
- On the admin page > collection centres > for each centre, allow the admin to decide some time slots when the centre is open:
- e.g. VXL = 10:00, 10:15, 10:30, 10:45, 11:00.....13:45
-Then, when a Volunteer Adds new parcel for collection, when they choose a collection time, show a drop down list with the pre-chosen time slots

**Comment by minalui** [comment]
Dev notes:
- Added time_slot column to collection centres that is of type collection_timeslot_type[]
- Collection_timeslot_type : {time: time without time zone; is_active: boolean}
- Added a time slots column to collection centres table in the admin panel with a button that opens the collection slots modal
- Modal opens to show a list of checkboxes with corresponding times
- Checkboxes can be checked or unchecked to demonstrate opening hours (checked = open, unchecked = closed)
- Save button to save changes to db
- Selected collection datetime displayed in parcels modal
- Available collection slot displayed when collection centre is selected

**Comment by minalui** [comment]
QA

As an admin user
- [x] I should see a collection centres table in the admin panel with a new column collection slots.
- [x] When I click on edit collection slots, it opens a modal to allow me to select and deselect when the collection centre is open
- [x] When I click save, my changes are saved into collection centre table in the database
Ticket raised for generating two audit logs [https://softwiretech.atlassian.net/browse/VFB-254](https://softwiretech.atlassian.net/browse/VFB-254)
- [x] If I create a new collection centre, the edit collection centre button is disabled until I click save

As a regular user
- [x] I can see "COLLECTION DATE TIME" in the parcels modal
- [x] When I edit/add a parcel, I can see the collection slots available for each collection centre (please edit some time slots to check)
- [x] If a collection centre does not have any collection slots set then an empty dropdown appears. Ticket raised for error handling [https://softwiretech.atlassian.net/jira/software/c/projects/VFB/boards/862/backlog?selectedIssue=VFB-247](https://softwiretech.atlassian.net/jira/software/c/projects/VFB/boards/862/backlog?selectedIssue=VFB-247)
- [x] If I save a parcel, the changes to collection slots are reflected in the parcels modal

**Comment by KylePUG** [comment]
QA check:

- On adding Collection Centre, on save "Edit Collection Slots" still greyed out. Becomes clickable on refresh. 
- On editing collection slots, if an error occurs two audit logs are sent (one success and one failure). Error message that results also flash on the modal for a split second before modal automatically closes; might be worth adding a error/success message modal after save.

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 3 months, presumed done
