### ISSUE TITLE
Parcel Status & Action naming - rename "Request Denied" to "Parcel Denied" - Remove wording 'Request"

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#235]
### Describe the solution / feature you'd like

- Select a Parcel
- Status drop down menu
- See "Request Denied" > Rename to "Parcel Denied"

- Select a Parcel
- Action drop down menu
- See "Delete Parcel Request" > Rename to "Delete Parcel"

I would say Request is old terminology from the 1st app where a client and parcel were lined together. Now they are separate entities i think we need to clearly label the status and actions, otherwise a new user might think deleting a Parcel might also delete  Client.

**Comment by AmeliaIsCoding** [comment]
Hi Dan, do you want the wording for the status "Request Deleted" to be changed to "Parcel Deleted" as well?

**Comment by dan-langridge** [comment]
Yes please, thank youOn 8 Apr 2024, at 10:32, AmeliaIsCoding ***@***.***> wrote:﻿
Hi Dan, do you want the wording for the status "Request Deleted" to be changed to "Parcel Deleted" as well?

**Comment by kaydentsoftwire** [comment]
QA steps:
- navigate to parcels page
- click 'actions' drop down - should display 'Delete Parcel'
- select one parcel and click 'Delete Parcel'
- click on the parcel in the table - it should show 'Parcel Deleted' as an event
- click 'statuses' drop down - should display 'Parcel Denied'
- click on a parcel and select 'Parcel Denied'
- click on the parcel in the table - it should show 'Parcel Denied' as an event
