### ISSUE TITLE
Remove Telephone Number as required field for User info

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#242]
### Describe the solution / feature you'd like

Telephone number is not really required by us, but I like that the option is there. Please can you make Phone number not required?

**Comment by rickaw** [comment]
## QA
When you invite a user using the following three methods, the user invite succeeds
- [ ] Without adding a phone number at all
- [ ] By adding a phone number
- [ ] By adding a phone number and then removing them before inviting the user

**Comment by minalui** [comment]
QA passed 👍
