### ISSUE TITLE
Parcels Page - Re-order Actions drop down menu

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#245]
### Describe the solution / feature you'd like

- On the Parcels Page
- Re-order the Actions drop down list to the following:

1. Day Overview
2. Lists
3. Labels
4. Generate Map
5. Driver Overview
6. Delete Parcel

This reflects the order of flow in the warehouse

**Comment by KylePUG** [comment]
## QA

- Navigate to 'Parcels' page
- Click on the 'Actions' drop-down menu
- [ ] The actions have been reordered as required, i.e.:
1. Download Day Overview
2. Download Shopping Lists
3. Download Shopping Labels
4. Generate Map
5. Download Driver Overview
6. Delete Parcel
- [ ] Each of the actions retain their functionalities

**Comment by kaydentsoftwire** [comment]
QA passed
