### ISSUE TITLE
Bulk Edit: Change Date of Multiple Parcels at once

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#302]
### Describe the solution / feature you'd like

There are some occasions where we need to move multiples parcels onto a different packing day.
The ability to select multiple parcels and change the packing date for all of them at once would be handy.
- Select all parcels
- Action
- Change Date
- Change Date popup appears with calendar picker 
- Submit

**Comment by dan-langridge** [comment]
A separate action to change the packing slot is a brilliant idea, thanks!Kind RegardsDan Langridge(+44) 07540 696683On 29 Apr 2024, at 09:26, Ricky Kawagishi ***@***.***> wrote:﻿
@dan-langridge Thanks for this. Would you also like to be able to pick the packing slot whilst changing the packing date? Or perhaps a separate action to set the packing slot for selected parcels?

**Comment by rickaw** [comment]
## Developer Notes
- Add a parcel action to set packing date of selected parcels
- Add a parcel adtion to set packing slot of selected parcels

**Comment by KylePUG** [comment]
QA:

- [ ] Check that packing slot/date is changed:
  - [x] Select a few parcels
  - [x] Under 'Actions' dropdown, click 'Change Packing Slot/Date'
  - [x] Before selecting a packing slot/date (i.e. leave the dropdown/date field blank), click change - a warning message should show - "Please choose a valid packing slot/date."
  - [x] Choose a packing slot/date to switch to and click 'Change'
  - [x] A success message (in the modal) should be shown - "Packing Slot/Date Changed to <packing_slot/packing_date>"
  - [x] Verify that the packing slot/date has been changed 
  - [x] A new status should also be seen after the change (can be seen on last status or in the modal on clicking the parcel) "Packing Slot/Date Changed (new packing slot/date: <packing_slot/packing_date> @ <date_of_change>"
  - [x] Repeat the steps for packing date/slot (note that a wider date range filter will be required to verify changes for packing date)
  - NOTE: Bug when changing packing slots (stay on success screen for a few seconds and refetch error messages come in) raised on JIRA https://softwiretech.atlassian.net/browse/VFB-246?atlOrigin=eyJpIjoiYWJiNGE2MzM0NDIyNDkxMzgxZjI4YmMxNzhlMWUzNDYiLCJwIjoiaiJ9

- [x] Check audit logs:
  - [x] After the changes made in the previous section, audit logs should be created. These are found under Admin > View Audit Logs
  - [x] Check that these are created for each of the modified parcels and that the actions were successful
  - [x] On clicking,
    - Client: displays a button that brings user to client details modal
    - Event: Packing Slot/Date Changed
    - Action Content: displays `{ "client_id": <client_id_key>, "parcel_id": <parcel_id_key>, "timestamp": <timestamp>, "event_data": "new packing slot/date: <newdate>", "new_parcel_status": "Packing Slot/Date Changed" }`

- [ ] Check error handling:
  - Run the website on local
  - [x] Check that if there is an error either in packing date/slot update or status update, this will be shown as an error message on clicking 'Change' in the date/slot change modal. This can be simulated by going to parcels > ActionBar > ActionModals > DateChangeModal.tsx and replacing packingSlotUpdateErrors with the test data given below. 
    - [x] Check that the error modal lists the parcels with errors
    - [x] Repeat this for SlotChangeModal.tsx
    - NOTE: formatting of the list of errors has been raised on JIRA https://softwiretech.atlassian.net/browse/VFB-249?atlOrigin=eyJpIjoiNzI0MjhkZWI1NzU3NDE2Mzg3ZTAxNGQzYjM5ZDBiNTMiLCJwIjoiaiJ9
  - [x] This step applies for SlotChangeModal.tsx only. Check that on replacing packingSlotsError to true in the if statement, when clicking Actions > Change Packing Slot, the modal only shows the error message - i.e. no dropdown list/action buttons.
  - [ ] Check that in the case of an update error, an audit log is sent with success = False. Simulate this by going to parcels > ActionBar > ActionModals > CommonDateAndSlot.tsx and replacing the argument in the final two if statements with true. 
  - [x] In CommonDateAndSlot.tsx, check that if `fetchError` occurs, an audit log is sent.


---
Test data
        `const packingSlotUpdateErrors: {
            parcelId: string | null;
            error: FetchParcelError | UpdateParcelError | null;
        }[] = [
            {parcelId: "bbabbc", error: {
                type: "failedToFetchParcel",
                logId: "kasndkfnakd",
            }},
            {parcelId: "efwef", error: {
                type: "noMatchingParcels",
                logId: "asdfadf",
            }},
            {parcelId: "asdfad", error: null}
        ]`

**Comment by minalui** [comment]
QA: Couple points

- [] Wonder if date calender should not accept retrospective dates (ie. before today)?
- [] Currently when testing for errors audit log gets sent twice (one success, one failure)

**Comment by KylePUG** [comment]
Added further actions on JIRA - will move this ticket forward :)

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 3 months, presumed done
