### ISSUE TITLE
Client modal - Free text box for storing notes about the client

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#303]
### Describe the solution / feature you'd like

Sometimes it would be helpful to store notes against a client, for example that they received a special item (not on the shopping list) in their last parcel like a Microwave, or any other notes that would be helpful to store.
- Open a client modal
- Scroll down to new NOTES text box
- Edit text
- Submit

**Comment by rickaw** [comment]
## Developer Notes
- Add a `notes` text field for clients
- Display the notes in client detail modal
- Add the notes field on the add / edit client form

**Comment by AmeliaIsCoding** [comment]
## Also included in the ticket
- Free text box for editing client notes directly from client modal

**Comment by AmeliaIsCoding** [comment]
## QA

- [x] In dev database `clients` table, there is a column `notes` of type string
- [x] In local database `clients` table, there is a column `notes` which is filled by a random string
- [x] In dev site, in Clients page, clicking on a client row to open its modal shows a field for Notes
- [x] There is no field for "Is Active"
- [x] The notes field is an editable text box with buttons for cancel and save
- [x] On typing something in the box and saving, closing and reopening the modal, the changes persist
- [x] On typing something in the box and cancelling, the text in the box reverts to the original text without needing to close and reopen
- [x] In the front end audit logs table in Admin page, an audit log row has been added with action "edit client notes", a link to the client whose notes you edited, and content populated with `clientId` and the notes that you added
- In local site, change the file src/app/c;lients/updateClientNotes.ts to force an error on submission - eg, change the table that is updated to a different string like "error expected". Try and edit the notes of a client as before. An error should be displayed in the modal that includes the log ID
- [x] The error disappears on each of the following: typing something else in the notes box, clicking "cancel", closing and reopening the modal
- [x] In the front end audit logs table in Admin page, an audit log row has been added with action "edit client notes", a link to the client whose notes you edited, and content populated with `clientId` and the notes that you added, and was success false, and log ID populated
- [x] Back in dev site, open a client modal, click "edit details", and scroll to the bottom. The notes should be visible as a text field, and editing the content saves correctly on submit
- [x] Create a new client; scroll to the bottom; the notes should be visible as a text field, with the content saving correctly when the client is made

**Comment by 8kristy** [comment]
Moving back to to-do, implementation here https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/pull/370 but needs review/tweaking

**Comment by stonelink** [comment]
## QA Passed

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 2 months, presumed done
