### ISSUE TITLE
Increase Size of TickBox on Parcels page

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#329]
### Describe the solution / feature you'd like

Increase the size of the tick box on the Parcels page (comically large is not an issue, the warehouse is cold and we use trackpads/ipads) so a large button is perfect, current app size button is good for us
<img width="239" alt="Screenshot 2024-05-13 at 20 19 34" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/80202270/e118405f-c9a6-488b-834a-bc3658eef79e">

**Comment by stonelink** [comment]
## QA Steps

Go to the Parcels page in the following browsers and check that the checkboxes are larger than before and behave as expected:
- Chrome
- Safari
- Edge

**Comment by stonelink** [comment]
QA Passed on Safari, Chrome, Edge

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 2 weeks, presumed done
